### ISSUE TITLE
Add examples with laravel/symfony integration

### ISSUE THREAD

**Issue by litan1106** [dapr/php-sdk#82]
## Describe the feature
Add examples with laravel/symfony integration

Most of us use laravel/symfony in real world applications.

**Comment by withinboredom** [comment]
Thanks for this, I was torn between adding a Swoole example or a Laravel example. This makes it easy :)

**Comment by litan1106** [comment]
@withinboredom is there an example of the DaprClient for PHP like the C# below? I really like the way the used the DaprClient in the dapr .net sdk.

getstate example
![image](https://user-images.githubusercontent.com/1310539/113887934-c14e4780-9776-11eb-8f88-d3abf47a0f02.png)
invocation example
![image](https://user-images.githubusercontent.com/1310539/113888477-3caff900-9777-11eb-8b82-254c8b7c6bf4.png)

**Comment by withinboredom** [comment]
Not with that kind of expression, not yet. That is coming with the GRPC client, however.

**Comment by withinboredom** [comment]
To invoke a state store, you use the `StateManager` object. There's not much for invocation because there's so many variants and it is basically a pass-through.

**Comment by litan1106** [comment]
@withinboredom or maybe something like the DaprClient with js-sdk.
I really like the simplicity of the other DaprClient usages in other Dapr sdks.

![image](https://user-images.githubusercontent.com/1310539/113890436-01162e80-9779-11eb-9f75-6eb193b27509.png)

**Comment by withinboredom** [comment]
Yeah, those are all generated by GRPC while that was not possible when the SDK was made, so it is all hand-written. 

Personally, I'm not a fan of the DaprClient in them because in those SDKs, it feels more like a god-object that is responsible for many unrelated things. Even with the GRPC client, the PHP SDK will still maintain backwards compatibility. Though I'm wary to actually implement it because the PHP GRPC libraries tend to lag behind the main GRPC development by at least a month, sometimes more.

**Comment by withinboredom** [comment]
@litan1106 I'm going to be spending the next few days on this, and I should have asked sooner: but what do you expect to use Laravel for? As a front-end client, or as a micro-service?
